### ISSUE TITLE
Redirect to authorize error

### ISSUE THREAD

**Issue by mrceresa** [CartoDB/carto-selfhosted-helm#98]
Thanks a lot for making this nice chart available!

I run the chart on a local k8s cluster created with docker desktop with the default parameters and everything seems to have been started correctly, but I can't login to the instance. If I go to 
https://carto-selfhosted.lan

which is locally mapped to 127.0.0.1, it tries to redirect me to 
https://authorize? 

which fails. Shouldn't it be 
https://carto-selfhosted.lan/authorize?

**Comment by ilbambino** [comment]
nice that you tried it out. But it seems that you don't have the configuration and licensing files that you get from CARTO when you signup for an account.

I will clarify that more in the README to avoid more future errors like yours.

If that's not the case and you still have some other issue please reopen or contact our support
